<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\LenderContactsModel;

class LenderContactsSeeder extends Seeder
{
    public function run()
    {
        LenderContactsModel::insert([
            [
                'lender_id' => 1,
                'contact_type' => 'NSW',
                'name' => 'Stewart Hickey',
                'email' => 'stewart.hickey@dynamoney.com',
                'mobile_number' => '0432 968 138',
                'title' => 'Senior Partner | Head of Commercial NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 1,
                'contact_type' => 'NSW',
                'name' => 'Caitie McCann',
                'email' => 'caitiem@dynamoney.com',
                'mobile_number' => '0480 039 366',
                'title' => 'Business Development Manager - NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 1,
                'contact_type' => 'NSW',
                'name' => 'Matt Nicolopoulos',
                'email' => 'matthewn@dynamoney.com',
                'mobile_number' => '0480 039 500',
                'title' => 'Business Development Manager - NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 1,
                'contact_type' => 'NSW',
                'name' => 'Elaine Song',
                'email' => 'elaines@dynamoney.com',
                'mobile_number' => '0480 039 368',
                'title' => 'Business Development Manager - NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 1,
                'contact_type' => 'QLD',
                'name' => 'Caleb Gunn',
                'email' => 'caleb.gunn@dynamoney.com',
                'mobile_number' => '0432 964 611',
                'title' => 'Senior Partner | Head of Commercial QLD',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 1,
                'contact_type' => 'QLD',
                'name' => 'Ellis Curran',
                'email' => 'ellisc@dynamoney.com',
                'mobile_number' => '0459 457 297',
                'title' => 'Business Development Manager - QLD',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 1,
                'contact_type' => 'QLD',
                'name' => 'Bradley Richter',
                'email' => 'bradley.richter@dynamoney.com',
                'mobile_number' => '0432 955 779',
                'title' => 'Business Development Manager - QLD',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 1,
                'contact_type' => 'VIC & TAS',
                'name' => 'Chanel Coombs',
                'email' => 'chanelc@dynamoney.com',
                'mobile_number' => '0484 790 456',
                'title' => 'Senior Partner | Head of Commercial VIC/TAS',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 1,
                'contact_type' => 'VIC & TAS',
                'name' => 'Stephen Davis',
                'email' => 'stephend@dynamoney.com',
                'mobile_number' => '0460 747 627',
                'title' => 'Business Development Manager - VIC',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 1,
                'contact_type' => 'VIC & TAS',
                'name' => 'Wayne Feng',
                'email' => 'waynef@dynamoney.com',
                'mobile_number' => '0474 444 878',
                'title' => 'Business Development Manager - VIC',
                'deleted_flag' => 0,
            ],

            [
                'lender_id' => 1,
                'contact_type' => 'SA & WA',
                'name' => 'Sierina Franklin',
                'email' => 'sierinaf@dynamoney.com',
                'mobile_number' => '0460 892 035',
                'title' => 'Business Development Manager – SA & WA',
                'deleted_flag' => 0,
            ],

            // Lumi contacts

            [
                'lender_id' => 3,
                'contact_type' => '',
                'name' => 'Stephen Lew',
                'email' => 'stephen.lew@lumi.com.au',
                'mobile_number' => '',
                'title' => 'BDM – Nationwide',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => '',
                'name' => 'Trent Mackie',
                'email' => 'trent.mackie@lumi.com.au',
                'mobile_number' => '',
                'title' => 'BDM – National',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => '',
                'name' => 'James Allen',
                'email' => 'james.allen@lumi.com.au',
                'mobile_number' => '0482 072 068',
                'title' => 'Sales Team Lead – Broker Accounts',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => '',
                'name' => 'John Clifford',
                'email' => 'john.clifford@lumi.com.au',
                'mobile_number' => '0415 427 695',
                'title' => 'Head of Broker',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => '',
                'name' => 'Marc Bianco',
                'email' => 'mark.bianco@lumi.com.au',
                'mobile_number' => '0482 093 924',
                'title' => '',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => 'NSW',
                'name' => 'Moneer Husari',
                'email' => 'moneer.husari@lumi.com.au',
                'mobile_number' => '0420 506 530',
                'title' => 'Senior BDM - NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => 'NSW & ACT',
                'name' => 'Mike Domjen',
                'email' => 'mike.domjen@lumi.com.au',
                'mobile_number' => '0477 573 377',
                'title' => 'BDM – NSW & ACT',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => 'NSW & ACT',
                'name' => 'Albert Challita',
                'email' => 'albert.challita@lumi.com.au',
                'mobile_number' => '0482 078 255',
                'title' => 'BDM – NSW & ACT',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => 'QLD/SA/WA',
                'name' => 'Graeme Bennett',
                'email' => 'graeme.bennett@lumi.com.au',
                'mobile_number' => '',
                'title' => 'BDM – QLD/SA/WA',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => 'VIC/TAS/SA',
                'name' => 'Reid Davidson',
                'email' => 'reid.davidson@lumi.com.au',
                'mobile_number' => '',
                'title' => 'BDM – VIC/TAS/SA',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => 'VIC/TAS/SA',
                'name' => 'Marko Milutinovic',
                'email' => 'marko.milutinovic@lumi.com.au',
                'mobile_number' => '',
                'title' => 'BDM – VIC/TAS/SA',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 3,
                'contact_type' => 'VIC',
                'name' => 'Jake Pianta',
                'email' => 'jake.pianta@lumi.com.au',
                'mobile_number' => '',
                'title' => 'BDM – VIC',
                'deleted_flag' => 0,
            ],


            [
                'lender_id' => 18,
                'contact_type' => 'NSW',
                'name' => 'Sahl Jappie',
                'email' => 'sjappie@banjoloans.com',
                'mobile_number' => '0477 893 411',
                'title' => 'Business Development Manager - NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 18,
                'contact_type' => 'NSW',
                'name' => 'Samantha McPherson',
                'email' => 'smcpherson@banjoloans.com',
                'mobile_number' => '0428 628 765',
                'title' => 'Business Development Manager - NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 18,
                'contact_type' => 'NSW',
                'name' => 'Joe Purcell',
                'email' => 'jpurcell@banjoloans.com',
                'mobile_number' => '0466 778 998',
                'title' => 'Business Development Manager - NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 18,
                'contact_type' => 'NSW',
                'name' => 'Haifa Sameer',
                'email' => 'hsameer@banjoloans.com',
                'mobile_number' => '0411 326 245',
                'title' => 'Direct Business Development Manager',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 18,
                'contact_type' => 'VIC/TAS/SA',
                'name' => 'Jason Gatt',
                'email' => 'jgatt@banjoloans.com',
                'mobile_number' => '0434 019 725',
                'title' => 'Southern Region Sales Manager',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 18,
                'contact_type' => 'VIC',
                'name' => 'Steven Dang',
                'email' => 'sdang@banjoloans.com',
                'mobile_number' => '0493 576 991',
                'title' => 'Business Development Manager - VIC',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 18,
                'contact_type' => 'VIC/SA/TAS',
                'name' => 'Vel Markovic',
                'email' => 'vmarkovic@banjoloans.com',
                'mobile_number' => '0493 371 194',
                'title' => 'Business Development Manager - VIC/SA/TAS',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 18,
                'contact_type' => 'QLD',
                'name' => 'Steven Kent',
                'email' => 'skent@banjoloans.com',
                'mobile_number' => '0433 075 561',
                'title' => 'Business Development Manager - QLD',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 18,
                'contact_type' => 'WA',
                'name' => 'Simon O\'Leary',
                'email' => 'soleary@banjoloans.com',
                'mobile_number' => '0422 867 909',
                'title' => 'Business Development Manager - WA',
                'deleted_flag' => 0,
            ],

            [
                'lender_id' => 9,
                'contact_type' => '',
                'name' => 'Ervin Robovic',
                'email' => 'ervinr@biigga.au',
                'mobile_number' => '0497 357 354',
                'title' => 'Business Development Manager',
                'deleted_flag' => 0,
            ],


            // bizcap
            [
                'lender_id' => 11,
                'contact_type' => '',
                'name' => 'Issac Garson',
                'email' => 'igarson@bizcap.com.au',
                'mobile_number' => '0420 234 805',
                'title' => 'Senior Business Development Manager',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 11,
                'contact_type' => '',
                'name' => 'Nathan Evans',
                'email' => 'nevans@bizcap.com.au',
                'mobile_number' => '0438 461 710',
                'title' => 'Senior Business Development Manager',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 11,
                'contact_type' => '',
                'name' => 'Mendy Ash',
                'email' => 'mash@bizcap.com.au',
                'mobile_number' => '0483 916 858',
                'title' => 'Senior Business Development Manager',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 11,
                'contact_type' => '',
                'name' => 'Queenie Jiang',
                'email' => 'qjiang@bizcap.com.au',
                'mobile_number' => '0485 878 364',
                'title' => 'Broker Relationships - Manager',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 11,
                'contact_type' => '',
                'name' => 'Clarisa Sylviana',
                'email' => 'csylviana@bizcap.com.au',
                'mobile_number' => '0483 914 151',
                'title' => 'Broker Relationship Specialist',
                'deleted_flag' => 0,
            ],

            [
                'lender_id' => 15,
                'contact_type' => '',
                'name' => 'Mick Burill',
                'email' => 'mick@bizfund.com.au',
                'mobile_number' => '0433 182 449',
                'title' => 'Sales Manager',
                'deleted_flag' => 0,
            ],


            // capify

            [
                'lender_id' => 12,
                'contact_type' => '',
                'name' => 'Danijel Trifkovic',
                'email' => 'dtrifkovic@capify.com.au',
                'mobile_number' => '0482 096 691',
                'title' => 'Business Development Manager – NSW, QLD & ACT',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 12,
                'contact_type' => '',
                'name' => 'James Ruddick',
                'email' => 'jruddick@capify.com.au',
                'mobile_number' => '0433 604 876',
                'title' => 'Business Development Manager – VIC, TAS, SA & WA',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 12,
                'contact_type' => '',
                'name' => 'Ziad Amin',
                'email' => 'zamin@capify.com.au',
                'mobile_number' => '0482 089 027',
                'title' => 'Senior Business Development Manager – NSW, QLD & ACT',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 12,
                'contact_type' => '',
                'name' => 'Leinnor Reyes',
                'email' => 'lreyes@capify.com.au',
                'mobile_number' => '0482 085 987',
                'title' => 'Business Development Manager – NSW, QLD & ACT',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 12,
                'contact_type' => '',
                'name' => 'Carlo Aoun',
                'email' => 'caoun@capify.com.au',
                'mobile_number' => '0482 095 957',
                'title' => 'Business Development Manager',
                'deleted_flag' => 0,
            ],

            [
                'lender_id' => 8,
                'contact_type' => '',
                'name' => 'Jeff Fiteni',
                'email' => 'jeff.fiteni@financeone.com.au',
                'mobile_number' => '0400 782 820',
                'title' => 'National BDM Manager',
                'deleted_flag' => 0,
            ],

            // finance one
            [
                'lender_id' => 8,
                'contact_type' => 'NSW, ACT',
                'name' => 'Kiran Nair',
                'email' => 'kiran.nair@financeone.com.au',
                'mobile_number' => '0476 902 871',
                'title' => 'BDM – NSW, ACT',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 8,
                'contact_type' => 'NSW',
                'name' => 'Karan Sharma',
                'email' => 'karan.sharma@financeone.com.au',
                'mobile_number' => '0437 628 778',
                'title' => 'BDM – NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 8,
                'contact_type' => 'NSW',
                'name' => 'Kyle Bowe',
                'email' => 'kyle.bowe@financeone.com.au',
                'mobile_number' => '0447 226 833',
                'title' => 'BDM – NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 8,
                'contact_type' => 'QLD North',
                'name' => 'Sarah Bauer',
                'email' => 'sarah.bauer@financeone.com.au',
                'mobile_number' => '0419 943 461',
                'title' => 'BDM – QLD North',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 8,
                'contact_type' => 'QLD South',
                'name' => 'David Munn',
                'email' => 'david.munn@financeone.com.au',
                'mobile_number' => '0428 274 762',
                'title' => 'BDM – QLD South',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 8,
                'contact_type' => 'QLD & WA',
                'name' => 'Cameron Layfield',
                'email' => 'cameron.layfield@financeone.com.au',
                'mobile_number' => '0460 556 568',
                'title' => 'BDM – QLD & WA',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 8,
                'contact_type' => 'VIC & TAS',
                'name' => 'Nicholas Lazarus',
                'email' => 'nicholas.lazarus@financeone.com.au',
                'mobile_number' => '0488 208 060',
                'title' => 'BDM – VIC & TAS',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 8,
                'contact_type' => 'SA & VIC',
                'name' => 'Melissa Romeo',
                'email' => 'melissa.romeo@financeone.com.au',
                'mobile_number' => '0428 870 297',
                'title' => 'BDM – SA & VIC',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 8,
                'contact_type' => 'VIC & SA',
                'name' => 'Rebekah Beale',
                'email' => 'rebekah.beale@financeone.com.au',
                'mobile_number' => '0418 307 904',
                'title' => 'BDM – VIC & SA',
                'deleted_flag' => 0,
            ],


            // funds now

            [
                'lender_id' => 17,
                'contact_type' => '',
                'name' => 'Jack Shultz',
                'email' => 'jack@fundsnow.com.au',
                'mobile_number' => '0490 784 834',
                'title' => 'Business Development Manager',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 17,
                'contact_type' => '',
                'name' => 'Luke Sylvester',
                'email' => 'luke@fundsnow.com.au',
                'mobile_number' => '',
                'title' => '',
                'deleted_flag' => 0,
            ],

            // moneytech

            [
                'lender_id' => 19,
                'contact_type' => '',
                'name' => 'Steven Godwin',
                'email' => 'steven.godwin@moneytech.com.au',
                'mobile_number' => '0432 300 686',
                'title' => 'National Sales Manager - Small Business',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 19,
                'contact_type' => '',
                'name' => 'Mariana Garcia',
                'email' => 'mariana.garcia@moneytech.com.au',
                'mobile_number' => '0405 078 004',
                'title' => 'BDM - Small Business NSW',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 19,
                'contact_type' => '',
                'name' => 'James Excell',
                'email' => 'james.excell@moneytech.com.au',
                'mobile_number' => '0414 640 715',
                'title' => 'BDM - Small Business VIC, TAS & SA',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 19,
                'contact_type' => '',
                'name' => 'Mahalia Fagan',
                'email' => 'mahalia.fagan@moneytech.com.au',
                'mobile_number' => '0423 860 410',
                'title' => 'BDM - Small Business QLD & WA',
                'deleted_flag' => 0,
            ],
            [
                'lender_id' => 19,
                'contact_type' => '',
                'name' => 'Mandela Opuku',
                'email' => 'mandela.opuku@moneytech.com.au',
                'mobile_number' => '0491 221 271',
                'title' => 'BDM',
                'deleted_flag' => 0,
            ],

        ]);
    }
}
